# This is the network config written by 'subiquity'
network:
  ethernets:
    eno1:
      addresses:
      - 5.189.239.114/24
      gateway4: 5.189.239.254
      nameservers:
        addresses:
        - 188.93.16.19
        - 188.93.17.19
        search: []
    eno2:
      addresses:
      - 192.168.0.1/24
  version: 2

